/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintItemObjectPageObjectPage journey");

        opaTest("Navigate to MaintItemObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMaintNotificationList.onFilterBar().iExecuteSearch();

            Then.onTheMaintNotificationList.onTable().iCheckRows();
            When.onTheMaintNotificationList.onTable().iPressRow(0);

            Then.onTheMaintNotificationObjectPage.iSeeThisPage();
            Then.onTheMaintNotificationObjectPage.onTable({ property: "_MaintItem" }).iCheckRows();
            When.onTheMaintNotificationObjectPage.onTable({ property: "_MaintItem" }).iPressRow(0);

            Then.onTheMaintItemObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMaintItemObjectPage.iCheckSection({ section: "General" });
            Then.onTheMaintItemObjectPage.onForm({ section: "General" }).iCheckField({ property: "ItemNo" });
            Then.onTheMaintItemObjectPage.onForm({ section: "General" }).iCheckField({ property: "ActivityCode" });
            Then.onTheMaintItemObjectPage.onForm({ section: "General" }).iCheckField({ property: "SparePartId" });
            Then.onTheMaintItemObjectPage.onForm({ section: "General" }).iCheckField({ property: "RequiredQty" });
            Then.onTheMaintItemObjectPage.onForm({ section: "General" }).iCheckField({ property: "QtyUom" });
            Then.onTheMaintItemObjectPage.onForm({ section: "General" }).iCheckField({ property: "ItemStatus" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});