/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintNotificationObjectPageObjectPage journey");

        opaTest("Navigate to MaintNotificationObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMaintNotificationList.onFilterBar().iExecuteSearch();

            Then.onTheMaintNotificationList.onTable().iCheckRows();
            When.onTheMaintNotificationList.onTable().iPressRow(0);

            Then.onTheMaintNotificationObjectPage.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheMaintNotificationObjectPage.onHeader().iCheckEdit({ visible: true });
            // When.onTheMaintNotificationObjectPage.onHeader().iPressEdit();
            Then.onTheMaintNotificationObjectPage.onHeader().iCheckAction("Start Work" /* , { enabled: true } */);
            // When.onTheMaintNotificationObjectPage.onHeader().iPressAction("Start Work");
            Then.onTheMaintNotificationObjectPage.onHeader().iCheckAction("Complete Work" /* , { enabled: true } */);
            // When.onTheMaintNotificationObjectPage.onHeader().iPressAction("Complete Work");
            Then.onTheMaintNotificationObjectPage.onHeader().iCheckAction("Cancel Notification" /* , { enabled: true } */);
            // When.onTheMaintNotificationObjectPage.onHeader().iPressAction("Cancel Notification");
            Then.onTheMaintNotificationObjectPage.onHeader().iCheckAction("Re Open" /* , { enabled: true } */);
            // When.onTheMaintNotificationObjectPage.onHeader().iPressAction("Re Open");
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMaintNotificationObjectPage.iCheckNumberOfSections(3);
            When.onTheMaintNotificationObjectPage.iPressSectionIconTabFilterButton("Header");
            Then.onTheMaintNotificationObjectPage.iCheckSection({ section: "Header" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "PlantID" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "EquipmentID" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "DamageCodeID" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "TechnicianID" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "FuncLocId" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Priority" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Status" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Description" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "Header" }).iCheckField({ property: "SlaHours" });
            When.onTheMaintNotificationObjectPage.iPressSectionIconTabFilterButton("TechnicianDetails");
            Then.onTheMaintNotificationObjectPage.iCheckSection({ section: "TechnicianDetails" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechFirstName" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechLastName" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechEmail" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechPhone" });
            Then.onTheMaintNotificationObjectPage.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechAvailability" });
            When.onTheMaintNotificationObjectPage.iPressSectionIconTabFilterButton("MaintItems");
            Then.onTheMaintNotificationObjectPage.iCheckSection({ section: "MaintItems" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});