/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintNotificationListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMaintNotificationList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMaintNotificationList.onFilterBar().iCheckFilterField("Plant");
            Then.onTheMaintNotificationList.onFilterBar().iCheckFilterField("Technician");
            Then.onTheMaintNotificationList.onFilterBar().iCheckFilterField("Status");
            Then.onTheMaintNotificationList.onFilterBar().iCheckFilterField("Priority");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheMaintNotificationList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheMaintNotificationList.onFilterBar().iExecuteSearch();
        //     Then.onTheMaintNotificationList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMaintNotificationList.onTable().iCheckCreate({ visible: true });
            // Then.ontheMaintNotificationList.onTable().iPressCreate();
            // Then.ontheMaintNotificationList.onTable().iPressDelete();
            Then.onTheMaintNotificationList.onTable().iCheckDelete({ visible: true });
            // Then.onTheMaintNotificationList.onTable().iPressAction("Change Priority");
            Then.onTheMaintNotificationList.onTable().iCheckAction("Change Priority", { enabled: false });
            // Then.onTheMaintNotificationList.onTable().iPressAction("Reassign Technician");
            Then.onTheMaintNotificationList.onTable().iCheckAction("Reassign Technician", { enabled: false });
            // Then.onTheMaintNotificationList.onTable().iPressAction("Create From Template");
            Then.onTheMaintNotificationList.onTable().iCheckAction("Create From Template", { enabled: false });
            Then.onTheMaintNotificationList.onTable().iCheckColumns(undefined, {"PlantID":{"header":"Plant"},"EquipmentID":{"header":"Equipment"},"DamageCodeID":{"header":"Damage Code"},"TechnicianID":{"header":"Technician"},"FuncLocId":{"header":"Functional location"},"Priority":{"header":"Priority"},"Status":{"header":"Status"},"SlaHours":{"header":"SLA Hours"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheMaintNotificationList.onFilterBar().iExecuteSearch();
            
            Then.onTheMaintNotificationList.onTable().iCheckRows();

            When.onTheMaintNotificationList.onTable().iPressRow(0);
            Then.onTheMaintNotificationObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});